version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/master:/data/"
      - "./master.conf:/etc/redis.conf"
    networks:
      - mongodb_mongocluster

  redis-slave-1:
    container_name: "redis-slave-1"
    image: redis
    ports:
      - "6380:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/slave:/data/"
      - "./slave.conf:/etc/redis.conf"
    depends_on:
      - redis-master
    networks:
      - mongodb_mongocluster

  redis-slave-2:
    container_name: "redis-slave-2"
    image: redis
    ports:
      - "6381:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/slave:/data/"
      - "./slave.conf:/etc/redis.conf"
    depends_on:
      - redis-master
    networks:
      - mongodb_mongocluster

  redis-sentinel:
    container_name: 'redis-sentinel'
    image: redis
    ports:
      - "26379:26379"
    command: "redis-server /etc/sentinel.conf --sentinel"
    volumes:
      - "./sentinel.conf:/etc/sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - mongodb_mongocluster

networks:
  mongodb_mongocluster:
    external: true

